version: "3.9"

services:
  btp_mtp_app:
    build: .
    container_name: btp_mtp_allocation_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PORT=8501
    restart: always
